Repository voxpupuli/voxpupuli-test, pull requests merged in 2022-03, with the labels that each got.

#71 rubocop: Naming/MethodParameterName: Add common short parameters names to AllowedNames
  rubocop.yml
Labels: enhancement

#70 rubocop: Disable Style/OptionalBooleanParameter
  rubocop.yml
Labels: enhancement

#72 Release 5.3.0
  CHANGELOG.md
  voxpupuli-test.gemspec
Labels: skip-changelog

#74 rubocop: Naming/PredicateName: Add is_to_s to AllowedMethods
  rubocop.yml
Labels: bug

#75 rubocop: Naming/PredicateName: Fix AllowedMethods default is_a?
  rubocop.yml
Labels: bug

#76 Release 5.3.1
  CHANGELOG.md
  voxpupuli-test.gemspec
Labels: skip-changelog
