Repository voxpupuli/voxpupuli-test, pull requests merged in 2023-04, with the labels that each got.

#101 CI: for Puppet 7, use 7.24 or newer
  .github/workflows/test.yml
Labels: skip-changelog

#103 Add Puppet 8 to CI matrix
  .github/workflows/test.yml
Labels: enhancement

#100 Release 5.6.1
  CHANGELOG.md
  voxpupuli-test.gemspec
Labels: skip-changelog

#104 bump gemspec version 5.6.1 -> 5.7.0
  voxpupuli-test.gemspec
Labels: skip-changelog

#105 Require Ruby 2.7 or newer, drop Puppet 6 support
  .github/workflows/test.yml
  voxpupuli-test.gemspec
Labels: backwards-incompatible

#107 puppet-strings: Require 4.x
  voxpupuli-test.gemspec
Labels: backwards-incompatible

#110 GCG: Add faraday-retry dep
  Gemfile
Labels: bug

#109 Build gems with verbosity and strictness
  .github/workflows/release.yml
  .github/workflows/test.yml
  voxpupuli-test.gemspec
Labels: enhancement
