Repository voxpupuli/voxpupuli-test, pull requests merged in 2024-07, with the labels that each got.

#130 Add rubocop config
  .github/workflows/test.yml
  .rubocop.yml
  .rubocop_todo.yml
  Gemfile
  Rakefile
  lib/voxpupuli/test.rb
  lib/voxpupuli/test/facts.rb
  lib/voxpupuli/test/rake.rb
  lib/voxpupuli/test/spec_helper.rb
  spec/facts_spec.rb
  spec/spec_helper.rb
  voxpupuli-test.gemspec
Labels: enhancement

#143 Release v8.1.0
  CHANGELOG.md
  voxpupuli-test.gemspec
Labels: skip-changelog

#144 custom facts: Honour stringified facts
  .rubocop_todo.yml
  lib/voxpupuli/test/facts.rb
Labels: bug

#132 require rspec-puppet-facts 5.x; drop legacy facts support
  voxpupuli-test.gemspec
Labels: backwards-incompatible

#145 Release 9.0.0
  CHANGELOG.md
  voxpupuli-test.gemspec
Labels: skip-changelog
