Repository voxpupuli/voxpupuli-test, pull requests merged in 2025-09, with the labels that each got.

#178 voxpupuli-puppet-lint-plugins: require 6.x
  voxpupuli-test.gemspec
Labels: backwards-incompatible

#179 dependabot: fix configuration
  .github/dependabot.yml
Labels: skip-changelog

#191 rspec-puppet-facts: Allow 6.x
  voxpupuli-test.gemspec
Labels: enhancement
